# Generated by Django 6.0.3 on 2026-03-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_task_ticket_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tasks.ticket')),
            ],
        ),
    ]
