# Generated by Django 6.0.3 on 2026-03-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_ticketphoto'),
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='users.station'),
        ),
    ]
