# Generated by Django 6.0.3 on 2026-04-02 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_rating_to_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename stale index left over from the Task↔Ticket model swap in 0004
        # (RenameModel didn't rename FK indexes, so tasks_task_created_by_id_1345568a
        # still lives on tasks_ticket and would clash with the new tasks_task FK index.)
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS tasks_task_created_by_id_1345568a RENAME TO tasks_ticket_created_by_id_1345568a;",
            reverse_sql="ALTER INDEX IF EXISTS tasks_ticket_created_by_id_1345568a RENAME TO tasks_task_created_by_id_1345568a;",
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
