# Generated by Django 6.0.3 on 2026-03-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_station_deputy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
