# Generated by Django 6.0.3 on 2026-03-06 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_station_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='deputy',
        ),
        migrations.AddField(
            model_name='station',
            name='deputies',
            field=models.ManyToManyField(blank=True, related_name='deputy_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
