# Generated by Django 6.0.3 on 2026-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('station_manager', 'Station Manager'), ('deputy', 'Deputy'), ('it_manager', 'IT Manager'), ('it_worker', 'IT Worker'), ('supply_worker', 'Supply Worker'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
    ]
