# Generated by Django 6.0.3 on 2026-03-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_phone_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('station_manager', 'Station Manager'), ('deputy', 'Deputy'), ('it_manager', 'IT Manager'), ('it_deputy', 'IT Deputy'), ('it_worker', 'IT Worker'), ('supply_worker', 'Supply Worker'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
        migrations.CreateModel(
            name='RoleInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('it_worker', 'IT Worker'), ('supply_worker', 'Supply Worker'), ('station_manager', 'Station Manager')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_invites', to='users.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_role_invites', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_invites', to='users.station')),
            ],
        ),
    ]
