# Generated by Django 6.0.3 on 2026-04-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_role_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinvite',
            name='role',
            field=models.CharField(choices=[('it_manager', 'IT Manager'), ('it_worker', 'IT Worker'), ('supply_worker', 'Supply Worker'), ('station_manager', 'Station Manager')], max_length=20),
        ),
    ]
